package TACSCMApp;


/**
* TACSCMApp/SCM.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from TACSCM.idl
* 28. august 2014 kl 12.03 CEST
*/

public interface SCM extends SCMOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface SCM
