package TACSCMApp;

/**
* TACSCMApp/SCMHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from TACSCM.idl
* 28. august 2014 kl 12.03 CEST
*/

public final class SCMHolder implements org.omg.CORBA.portable.Streamable
{
  public TACSCMApp.SCM value = null;

  public SCMHolder ()
  {
  }

  public SCMHolder (TACSCMApp.SCM initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = TACSCMApp.SCMHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    TACSCMApp.SCMHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return TACSCMApp.SCMHelper.type ();
  }

}
