package TACSCMApp;


/**
* TACSCMApp/SCMOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from TACSCM.idl
* 28. august 2014 kl 12.03 CEST
*/

public interface SCMOperations 
{
  String send (String str);
  boolean status ();
  short getTime ();
  double getInterestRate ();
  double getLoanInterestRate ();
  double getStorageCost ();
} // interface SCMOperations
